# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = match:title ^(pavucontrol)$ ,float  on
windowrule = match:title ^(blueman-manager)$, float on
windowrule = match:title ^(nm-connection-editor)$,float on
windowrule = match:title ^(qalculate-gtk)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrulev = workspace 9, match:class:^(ckemu)$
