#!/home/sof/.local/share/pipx/venvs/pyghidra/bin/python
import sys
from pyghidra.gui import _gui
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(_gui())
